### ISSUE TITLE
Default eeprom.hex is missing

### ISSUE THREAD

**Issue by saper** [arvydas/blinkstick-firmware#1]
It seems the default `eeprom.hex` file is missing - without it `make defaults` won't work

**Comment by dunk8888** [comment]
Yes they are all missing from all firmware maybe  he doesnt want us making our own serial numbers as this will mess other peoples sticks up that are used remotely online if we use the same serial on our own sticks or our own builds,thats what i think,i supose he needs to keep track on what serials people have as each stick has to be different i suppose,ime not sure how serials are genarated maybe a keygen or he does it manual,he said to me just make defaults but it does need an eeprom with somthing in it,ive been messing about with it for weeks,ive asked about this a few times!I can make the eeproms another way and put in any serial i like but dont like to because of the reason stated above, but would be nice to use the firmware as intended as this bugs me.it shouldnt be open source realy lol

**Comment by arvydas** [comment]
@saper added default eeprom. Rename the file to eeprom.hex and you should be good to go.
